[[language]]
name = "html"
auto-format = true
formatter = { command = "djlint", args = ["-", "--reformat", "--quiet"] }

[language-server.djlsp.{{ project_name }}]
django_settings_modules="{{ project_name }}.settings"
